### ISSUE TITLE
FILECOIN + TEXTILE = DATA 

### ISSUE THREAD

**Issue by raquelic** [protocol/polygon-grants#1]
TRACK 1: FILECOIN + TEXTILE = DATA: The best use of the Filecoin~Polygon Bridge to shuttle user-generated dApp data to Filecoin. Examples including consumer facing dApps that store user data on Filecoin via Bridges, decentralized content distribution applications, gaming platforms and tools that storage assets on IPFS + Filecoin, etc. Almost anything that replaces backend storage with Bridges.

**Comment by yrik** [comment]
Hey Hey! I plan to put the NFT collection for the https://cryptosnails.io game into textile. Is there a way to put there directly the whole folder? And another question, how do I submit for a bounty? Just make an empty PR here, with a link to the project repo (relevant commit) and description of functionality?

**Comment by lksbrssr** [comment]
hi @yrik - you can ask technical questions on the hackathon-Discord channel (https://discord.gg/4V9RrQcqm6) or on the IPFS Discord in hackathons-help (https://discord.gg/BprG7X9faE). You can learn about how to submit a bounty here: https://hidorahacks.medium.com/polygon-grants-hackathon-application-guide-1d5c07817d9d

**Comment by lksbrssr** [comment]
Sorry for the tardy reply!

**Comment by clairedora** [comment]
Hey @yrik This is Claire from DoraHacks! Please kindly check the guidelines for bounty hunters to tackle a bounty [https://hidorahacks.medium.com/how-does-a-bounty-hunter-tackle-a-hackerlink-bounty-5d2dd33716ac](https://hidorahacks.medium.com/how-does-a-bounty-hunter-tackle-a-hackerlink-bounty-5d2dd33716ac)

**Comment by ZhangPeibin** [comment]
hey ! I want to do this！
1. We will provide a platform where users can log in with metamask or other web3 wallets, or log in with Magic. No matter which wallet or Magic is used to log in, a user identities recognized by the textile will be produced.
2. We will use this user identities to link the user to the textile ThreadDB.and user data and MFS-like data uploaded by users to IPFS&FILECOIN will be stored in their own ThreadDB.
3. Users will be able to upload data in a textile bucket or use web3.storage to upload data. We will tell users how to bind textile or web3.storage through a tutorial
4. The user can encrypt the data through the user's unique identification, so that even if others know the cid of the data, it cannot be decrypted, and the user can decrypt the data and download it. You can also delete the files on the MFS

**Comment by ZhangPeibin** [comment]
> hey ! I want to do this！
> 
> 1. We will provide a platform where users can log in with metamask or other web3 wallets, or log in with Magic. No matter which wallet or Magic is used to log in, a user identities recognized by the textile will be produced.
> 2. We will use this user identities to link the user to the textile ThreadDB.and user data and MFS-like data uploaded by users to IPFS&FILECOIN will be stored in their own ThreadDB.
> 3. Users will be able to upload data in a textile bucket or use web3.storage to upload data. We will tell users how to bind textile or web3.storage through a tutorial
> 4. The user can encrypt the data through the user's unique identification, so that even if others know the cid of the data, it cannot be decrypted, and the user can decrypt the data and download it. You can also delete the files on the MFS

If there is a problem, please tell me, let us discuss how to solve this in a good way

**Comment by lksbrssr** [comment]
Hey @ZhangPeibin! Looking forward to what you're building there. I would like to encourage you to join the event's Discord to ask questions too: https://discord.gg/PxSbBbxr

**Comment by ZhangPeibin** [comment]
hey @lksbrssr , Okay , and How do I know that I am allowed to participate in this development?

**Comment by ZhangPeibin** [comment]
we want use this plan to develop a new website and store "Documentary"
All "documentaries" will create "metadata" and record on the chain
We contacted some documentary authors who are also very interested in this. The documentary itself records a true story that happened in the past, and storing it in filecoin will provide latecomers with a better understanding of what was sent before.

**Comment by lksbrssr** [comment]
@ZhangPeibin what is true for Encode is true for all other hackathons, too: You cannot submit a project that you received funding for as part of the grants program. If you would like to continue building on a grants-project please contact the grants team with a new/updated proposal.

**Comment by ZhangPeibin** [comment]
This is a new project and has nothing to do with DDshare.We recently held some offline exchanges and some partners interested in decentralized storage。
We ultimately want to build a website that records "documentaries", using Filecoin and textile to permanently save video resources, and when uploading data, we will keep the details of "documentaries" on the chain.
We now have a documentary director, and also contacted Charles Cao of Filswan, who gave us some suggestions on the storage node and helped us solve these problems.

**Comment by ZhangPeibin** [comment]
We know that documentary is to record the real things that have happened in the past. I believe that in the future, many people can view the things sent in the past through this website, whether it is animals, humanities, technology or other, this is to get the real things in the past. a place.

The documentary directors we have contacted have a lot of resources, and they are also looking for a decentralized storage method to record these. This is very meaningful.

**Comment by ZhangPeibin** [comment]
Why watch a documentary? The answer is the same as why you want to make a documentary.
To understand others-documentaries are the best way to meet this need.
Understand the world around you; understand different ways of life; understand different countries; understand the value of different outlooks on life; understand how other species survive...
The documentary provides us with: a link to connect with the surrounding world and exchange feelings.
For those of you who are unwilling to live only once, documentaries are the most effective way for us to touch the larger world.
People who don't watch documentaries are sad because they only have one life.

So when we use Filecoin and textile to save documentaries, after a few years, people will remember that there is such a platform that can be traced back to the world sent.

**Comment by william-weber** [comment]
Hello, I would like to build this. Is this bounty still available?

**Comment by clairedora** [comment]
> Hello, I would like to build this. Is this bounty still available?

Yes still open for application!

**Comment by william-weber** [comment]
Great! I've already gotten started. It will be an MVP for a distributed CDN.
